### ISSUE TITLE
Is this maintained?

### ISSUE THREAD

**Issue by p0wl** [masahirompp/graphql-codegen-aws-lambda-types#1]
Hey 👋 just found your repository when searching for a good way to generate types for our appsync lambda resolvers.

Are you using your library in production? I'm currently fiddeling around with the "typescript-resolvers" plugin and am trying to configure that to use the `AppSyncResolverHandler` from 'aws-lambda' as Resolver function, which works okayish.

Anyway, thanks for your library 🙏 , would love to hear if you are using it or if you found another way to generate nice types for lambda handlers :)

**Comment by masahirompp** [comment]
@p0wl Hello. I'm using this library in production and it's okay.
I would be happy if you could try using this.
